server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://LOKI_HOST/loki/api/v1/push  # LOKI_HOST is the host of the Loki server

scrape_configs:
  - job_name: solana-rpc
    static_configs:
      - targets:
          - localhost  
        labels:
          job: solana-rpc
          host: HOSTNAME  # Hostname of the node
          environment: ENVIRONMENT  # Environment name
          __path__: LOG_PATH  # Path to the log file
